export const Constants = {
  AUTH_ACCESS_TOKEN: 'AUTH_ACCESS_TOKEN',
  AUTH_ACCESS_TTL: 'AUTH_ACCESS_TLL',
  AUTH_REFRESH_TOKEN: 'AUTH_REFRESH_TOKEN',
  AUTH_SESSION: 'AUTH_SESSION',
  AUTH_USERNAME: 'AUTH_USERNAME',
  LOGOUT_URL: '/logout',
  REFRESH_AUTH_URL: '/refresh-auth',
};

export const DytePoint = {
  CONTENT_VIEWED: 1,
  MODULE_COMPLETED: 10,
  LESSON_COMPLETED: 20,
};
